#!/usr/bin/env bash
# send a file from the client to the server using ssh scp utility

if [ $# -lt 3 ];
then 
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY";
	exit;
fi;

if [ $# -ge 4 ];
then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
else
	scp -o StrictHostKeyChecking=no -i "$1" "$3"@"$2":~/
fi;
	
